# Tensor的属性设置

In [1]:
import torch

## 指定Tensor的设备
- 在PyTorch中，可以通过`torch.device`来指定Tensor的设备。常用的设备包括CPU和GPU。
- 使用`torch.device("cpu")`来指定CPU设备。
- 如果只有有一个显卡，则使用`torch.device("cuda")`来制定GPU设备；如果有多张显卡，则使用`torch.device("cuda:0")`来指定第一个GPU设备。

In [2]:
# 设置设备
dev = torch.device("cuda:0")

In [3]:
a = torch.tensor([[0, 1, 2], [2, 0, 1]])  # 创建张量，不指定设备的情况下默认为 CPU
print(a)
print(a.type())

tensor([[0, 1, 2],
        [2, 0, 1]])
torch.LongTensor


In [4]:
b = torch.tensor([[0, 1, 2], [2, 0, 1]], device=dev)  # 创建张量并指定设备
print(b)
print(b.type())

tensor([[0, 1, 2],
        [2, 0, 1]], device='cuda:0')
torch.cuda.LongTensor


## 稀疏张量
- 创建稀疏张量需要指定索引和对应的值。
- 使用`torch.sparse_coo_tensor(indices, values, size)`来创建稀疏张量
- 其中`indices`是一个二维张量，`values`是一个一维张量，`size`是元组，示稀疏张量的形状。
- `indices`的每一列表示一个非零元素的位置，`values`的每个元素对应于`indices`中相应位置的值。
- `indices`的坐标描述规则类似numpy的shape。
- 稀疏张量可以通过`to_dense()`方法转换为稠密张量。

In [5]:
indices = torch.tensor([[2, 1, 0],[0, 1, 2], [0, 1, 2]])
values = torch.tensor([3, 4, 5])
c = torch.sparse_coo_tensor(indices, values, (3, 3, 3))
print(c)
print(c.type())
print(c.to_dense())  # 转换为稠密张量

tensor(indices=tensor([[2, 1, 0],
                       [0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([3, 4, 5]),
       size=(3, 3, 3), nnz=3, layout=torch.sparse_coo)
torch.sparse.LongTensor
tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 5]],

        [[0, 0, 0],
         [0, 4, 0],
         [0, 0, 0]],

        [[3, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])


In [6]:
# 指定稀疏张量的类型和设备
d = torch.sparse_coo_tensor(indices, values, (3, 3, 3), dtype=torch.float32, device=dev)
print(d)
print(d.type())

tensor(indices=tensor([[2, 1, 0],
                       [0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([3., 4., 5.]),
       device='cuda:0', size=(3, 3, 3), nnz=3, layout=torch.sparse_coo)
torch.cuda.sparse.FloatTensor
